In [1]:
import numpy as np
import pandas as pd
from openfisca_core import periods
import openfisca_france

In [2]:
population = pd.read_csv('population_simulated_men6310.csv')
pop = population[['salaire', 'salaire_conj', 'age', 'age_conj', 'nb_enf', 'statut_marital', 'retraite', 'retraite_conj']]
#pop.head()
pop

,salaire,salaire_conj,age,age_conj,nb_enf,statut_marital,retraite,retraite_conj
0,4190.0,0.0,22,21.0,1,1,0.0,0.0
1,9749.0,0.0,23,22.0,3,1,0.0,0.0
2,13509.0,0.0,25,23.0,0,1,0.0,0.0
3,13509.0,0.0,25,24.0,1,1,0.0,0.0
4,13509.0,21487.0,25,25.0,2,1,0.0,0.0
5,13509.0,31991.0,25,25.0,3,1,0.0,0.0
6,16464.0,19563.0,27,26.0,0,1,0.0,0.0
7,0.0,0.0,28,26.0,1,1,0.0,0.0
8,0.0,17479.0,28,26.0,0,1,0.0,0.0
9,16464.0,0.0,27,27.0,0,1,0.0,0.0
10,15991.0,0.0,26,27.0,2,1,0.0,0.0
11,0.0,14667.0,28,27.0,2,1,0.0,0.0
12,9749.0,20749.0,23,27.0,2,1,0.0,0.0
13,13509.0,18611.0,25,27.0,1,1,0.0,0.0
14,15991.0,19728.0,26,27.0,0,1,0.0,0.0
15,0.0,26407.0,28,27.0,2,1,0.0,0.0
16,0.0,21008.0,28,27.0,1,1,0.0,0.0
17,20034.0,23581.0,29,27.0,0,1,0.0,0.0
18,0.0,18165.0,28,27.0,1,1,0.0,0.0
19,20034.0,0.0,29,28.0,4,1,0.0,0.0
20,0.0,0.0,28,28.0,2,1,0.0,0.0
21,0.0,20660.0,28,28.0,2,1,0.0,0.0
22,13509.0,20481.0,25,28.0,4,1,0.0,0.0
23,16464.0,21796.0,27,28.0,1,1,0.0,0.0
24,0.0,22226.0,28,29.0,0,1,0.0,0.0
25,37990.0,17008.0,30,29.0,1,1,0.0,0.0
26,13509.0,0.0,25,29.0,0,1,0.0,0.0
27,20034.0,21529.0,29,29.0,1,1,0.0,0.0
28,15991.0,8792.0,26,29.0,0,1,0.0,0.0
29,16464.0,0.0,27,29.0,3,1,0.0,0.0
...,...,...,...,...,...,...,...,...
6280,0.0,NaN,85,NaN,0,2,1687.0,NaN
6281,0.0,NaN,85,NaN,1,2,1687.0,NaN
6282,0.0,NaN,86,NaN,0,2,1687.0,NaN
6283,0.0,NaN,86,NaN,0,0,1687.0,NaN
6284,0.0,NaN,86,NaN,0,0,1687.0,NaN
6285,0.0,NaN,86,NaN,0,0,1687.0,NaN
6286,0.0,NaN,86,NaN,0,0,1687.0,NaN
6287,0.0,NaN,87,NaN,0,3,1687.0,NaN
6288,0.0,NaN,87,NaN,0,2,1687.0,NaN
6289,0.0,NaN,87,NaN,4,2,1687.0,NaN
6290,0.0,NaN,87,NaN,0,2,1687.0,NaN
6291,0.0,NaN,89,NaN,0,2,1687.0,NaN
6292,25028.0,NaN,89,NaN,0,2,0.0,NaN
6293,0.0,NaN,89,NaN,0,0,1687.0,NaN
6294,0.0,NaN,89,NaN,0,2,1687.0,NaN
6295,0.0,NaN,89,NaN,0,2,1687.0,NaN
6296,0.0,NaN,90,NaN,0,2,1687.0,NaN
6297,0.0,NaN,90,NaN,0,2,1687.0,NaN
6298,0.0,NaN,90,NaN,0,2,1687.0,NaN
6299,0.0,NaN,91,NaN,0,2,1687.0,NaN
6300,0.0,NaN,91,NaN,0,2,1687.0,NaN
6301,0.0,NaN,91,NaN,0,0,1687.0,NaN
6302,0.0,NaN,92,NaN,0,3,1687.0,NaN
6303,0.0,NaN,92,NaN,0,2,1687.0,NaN
6304,0.0,NaN,92,NaN,0,2,1687.0,NaN
6305,0.0,NaN,93,NaN,0,2,1687.0,NaN
6306,0.0,NaN,93,NaN,0,2,1687.0,NaN
6307,0.0,NaN,93,NaN,0,0,1687.0,NaN
6308,0.0,NaN,94,NaN,0,2,1687.0,NaN
6309,0.0,NaN,95,NaN,0,2,1687.0,NaN

In [3]:
tbf = openfisca_france.FranceTaxBenefitSystem()

In [4]:
scenario = tbf.new_scenario()

In [5]:
year = periods.period('2016')

In [6]:
scenario.init_single_entity(period=year, parent1={})

In [7]:
simulation = scenario.new_simulation()

In [8]:
population[['salaire', 'salaire_conj', 'statut_marital']]

      salaire  salaire_conj  statut_marital
0      4190.0           0.0               1
1      9749.0           0.0               1
2     13509.0           0.0               1
3     13509.0           0.0               1
4     13509.0       21487.0               1
5     13509.0       31991.0               1
6     16464.0       19563.0               1
7         0.0           0.0               1
8         0.0       17479.0               1
9     16464.0           0.0               1
10    15991.0           0.0               1
11        0.0       14667.0               1
12     9749.0       20749.0               1
13    13509.0       18611.0               1
14    15991.0       19728.0               1
15        0.0       26407.0               1
16        0.0       21008.0               1
17    20034.0       23581.0               1
18        0.0       18165.0               1
19    20034.0           0.0               1
20        0.0           0.0               1
21        0.0       20660.0               1
22    13509.0       20481.0               1
23    16464.0       21796.0               1
24        0.0       22226.0               1
25    37990.0       17008.0               1
26    13509.0           0.0               1
27    20034.0       21529.0               1
28    15991.0        8792.0               1
29    16464.0           0.0               1
...       ...           ...             ...
6280      0.0           NaN               2
6281      0.0           NaN               2
6282      0.0           NaN               2
6283      0.0           NaN               0
6284      0.0           NaN               0
6285      0.0           NaN               0
6286      0.0           NaN               0
6287      0.0           NaN               3
6288      0.0           NaN               2
6289      0.0           NaN               2
6290      0.0           NaN               2
6291      0.0           NaN               2
6292  25028.0           NaN               2
6293      0.0           NaN               0
6294      0.0           NaN               2
6295      0.0           NaN               2
6296      0.0           NaN               2
6297      0.0           NaN               2
6298      0.0           NaN               2
6299      0.0           NaN               2
6300      0.0           NaN               2
6301      0.0           NaN               0
6302      0.0           NaN               3
6303      0.0           NaN               2
6304      0.0           NaN               2
6305      0.0           NaN               2
6306      0.0           NaN               2
6307      0.0           NaN               0
6308      0.0           NaN               2
6309      0.0           NaN               2

[6310 rows x 3 columns]

In [9]:
salaire_individus = []
idfoy = []
quifoy = []
for index, row in population.iterrows():
    salaire_individus.append(row['salaire'])
    idfoy.append(index)
    quifoy.append(0)
    if row['statut_marital'] == 1:
        salaire_individus.append(row['salaire_conj'])
        idfoy.append(index)
        quifoy.append(1)
salaire_individus = np.array(salaire_individus)
idfoy = np.array(idfoy)
quifoy = np.array(quifoy)

In [10]:
simulation.get_or_new_holder('salaire_de_base').set_input(year, salaire_individus)

In [11]:
foyer_fiscal = simulation.entities['foyer_fiscal']
foyer_fiscal.members_legacy_role = quifoy
foyer_fiscal.members_entity_id = idfoy
foyer_fiscal.count = max(idfoy) + 1
foyer_fiscal._members_role = None
simulation.entities['individu'].count = len(salaire_individus)

In [13]:
irpp = simulation.calculate('irpp', period=year)

In [20]:
population['irpp'] = irpp

In [21]:
population

,Unnamed: 0,activite,activite_conj,age,age_conj,emploi,emploi_conj,etudes,etudes_conj,handicap,...,salaire,salaire_conj,sexe,sexe_conj,statut_marital,statut_marital_conj,type_fam,enfant,nb_enf,irpp
0,0,True,False,22,21.0,True,False,False,True,False,...,4190.0,0.0,femme,homme,1,1.0,Couples,True,1,0.000000
1,1,True,False,23,22.0,True,False,False,False,False,...,9749.0,0.0,femme,homme,1,1.0,Couples,True,3,0.000000
2,2,True,False,25,23.0,True,False,True,True,False,...,13509.0,0.0,femme,homme,1,1.0,Couples,False,0,0.000000
3,3,True,False,25,24.0,True,False,True,False,False,...,13509.0,0.0,femme,homme,1,1.0,Couples,True,1,0.000000
4,4,True,True,25,25.0,True,True,True,False,False,...,13509.0,21487.0,femme,homme,1,1.0,Couples,True,2,0.000000
5,5,True,True,25,25.0,True,True,True,False,False,...,13509.0,31991.0,femme,homme,1,1.0,Couples,True,3,0.000000
6,6,True,True,27,26.0,True,True,False,False,False,...,16464.0,19563.0,femme,homme,1,1.0,Couples,False,0,0.000000
7,7,False,False,28,26.0,False,False,False,False,False,...,0.0,0.0,femme,homme,1,1.0,Couples,True,1,0.000000
8,8,False,True,28,26.0,False,True,False,False,False,...,0.0,17479.0,femme,homme,1,1.0,Couples,False,0,0.000000
9,9,True,True,27,27.0,True,False,False,False,False,...,16464.0,0.0,femme,homme,1,1.0,Couples,False,0,0.000000
10,10,True,True,26,27.0,True,False,False,False,False,...,15991.0,0.0,femme,homme,1,1.0,Couples,True,2,0.000000
11,11,False,True,28,27.0,False,True,False,False,False,...,0.0,14667.0,femme,homme,1,1.0,Couples,True,2,0.000000
12,12,True,True,23,27.0,True,True,False,False,False,...,9749.0,20749.0,femme,homme,1,1.0,Couples,True,2,0.000000
13,13,True,True,25,27.0,True,True,True,False,False,...,13509.0,18611.0,femme,homme,1,1.0,Couples,True,1,0.000000
14,14,True,True,26,27.0,True,True,False,False,False,...,15991.0,19728.0,femme,homme,1,1.0,Couples,False,0,0.000000
15,15,False,True,28,27.0,False,True,False,False,False,...,0.0,26407.0,femme,homme,1,1.0,Couples,True,2,0.000000
16,16,False,True,28,27.0,False,True,False,False,False,...,0.0,21008.0,femme,homme,1,1.0,Couples,True,1,0.000000
17,17,True,True,29,27.0,True,True,False,False,False,...,20034.0,23581.0,femme,homme,1,1.0,Couples,False,0,0.000000
18,18,False,True,28,27.0,False,True,False,False,False,...,0.0,18165.0,femme,homme,1,1.0,Couples,True,1,0.000000
19,19,True,False,29,28.0,True,False,False,False,False,...,20034.0,0.0,femme,homme,1,1.0,Couples,True,4,0.000000
20,20,False,False,28,28.0,False,False,False,False,False,...,0.0,0.0,femme,homme,1,1.0,Couples,True,2,0.000000
21,21,False,True,28,28.0,False,True,False,False,False,...,0.0,20660.0,femme,homme,1,1.0,Couples,True,2,0.000000
22,22,True,True,25,28.0,True,True,True,False,False,...,13509.0,20481.0,femme,homme,1,1.0,Couples,True,4,0.000000
23,23,True,True,27,28.0,True,True,False,False,False,...,16464.0,21796.0,femme,homme,1,1.0,Couples,True,1,0.000000
24,24,False,True,28,29.0,False,True,False,False,False,...,0.0,22226.0,femme,homme,1,1.0,Couples,False,0,0.000000
25,25,True,True,30,29.0,True,True,False,False,False,...,37990.0,17008.0,femme,homme,1,1.0,Couples,True,1,-2632.097900
26,26,True,False,25,29.0,True,False,True,False,False,...,13509.0,0.0,femme,homme,1,1.0,Couples,False,0,0.000000
27,27,True,True,29,29.0,True,True,False,False,False,...,20034.0,21529.0,femme,homme,1,1.0,Couples,True,1,0.000000
28,28,True,True,26,29.0,True,True,False,False,False,...,15991.0,8792.0,femme,homme,1,1.0,Couples,False,0,0.000000
29,29,True,True,27,29.0,True,False,False,False,False,...,16464.0,0.0,femme,homme,1,1.0,Couples,True,3,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6280,6280,False,NaN,85,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6281,6281,False,NaN,85,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,True,1,0.000000
6282,6282,False,NaN,86,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6283,6283,False,NaN,86,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6284,6284,False,NaN,86,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6285,6285,False,NaN,86,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6286,6286,False,NaN,86,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6287,6287,False,NaN,87,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,3,NaN,homme solo,False,0,0.000000
6288,6288,False,NaN,87,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6289,6289,False,NaN,87,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,True,4,0.000000
6290,6290,False,NaN,87,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6291,6291,False,NaN,89,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6292,6292,True,NaN,89,NaN,True,NaN,False,NaN,False,...,25028.0,NaN,homme,NaN,2,NaN,homme solo,False,0,-941.598022
6293,6293,False,NaN,89,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6294,6294,False,NaN,89,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6295,6295,False,NaN,89,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6296,6296,False,NaN,90,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6297,6297,False,NaN,90,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6298,6298,False,NaN,90,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6299,6299,False,NaN,91,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6300,6300,False,NaN,91,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6301,6301,False,NaN,91,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6302,6302,False,NaN,92,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,3,NaN,homme solo,False,0,0.000000
6303,6303,False,NaN,92,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6304,6304,False,NaN,92,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6305,6305,False,NaN,93,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6306,6306,False,NaN,93,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6307,6307,False,NaN,93,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,0,NaN,homme solo,False,0,0.000000
6308,6308,False,NaN,94,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000
6309,6309,False,NaN,95,NaN,False,NaN,False,NaN,False,...,0.0,NaN,homme,NaN,2,NaN,homme solo,False,0,0.000000

In [33]:
population.salaire_conj.mean()

14644.952794357027

In [22]:
population[population['irpp'] != 0]

,Unnamed: 0,activite,activite_conj,age,age_conj,emploi,emploi_conj,etudes,etudes_conj,handicap,...,salaire,salaire_conj,sexe,sexe_conj,statut_marital,statut_marital_conj,type_fam,enfant,nb_enf,irpp
25,25,True,True,30,29.0,True,True,False,False,False,...,37990.0,17008.0,femme,homme,1,1.0,Couples,True,1,-2632.097900
32,32,True,True,30,29.0,True,True,False,False,False,...,37990.0,23273.0,femme,homme,1,1.0,Couples,True,1,-2632.097900
33,33,True,True,30,29.0,True,True,False,False,False,...,37990.0,11642.0,femme,homme,1,1.0,Couples,False,0,-2632.097900
34,34,True,True,31,29.0,True,True,False,False,False,...,20850.0,55527.0,femme,homme,1,1.0,Couples,True,3,-198.216736
41,41,True,True,31,30.0,True,True,False,False,False,...,20850.0,5627.0,femme,homme,1,1.0,Couples,True,2,-198.216736
42,42,True,True,34,30.0,True,True,False,False,False,...,32146.0,21351.0,femme,homme,1,1.0,Couples,True,2,-1910.210571
47,47,True,False,30,30.0,True,False,False,False,False,...,37990.0,0.0,femme,homme,1,1.0,Couples,True,1,-2632.097900
50,50,True,True,31,31.0,True,True,False,False,False,...,20850.0,23240.0,femme,homme,1,1.0,Couples,False,0,-198.216736
51,51,True,True,34,31.0,True,True,False,False,False,...,32146.0,21696.0,femme,homme,1,1.0,Couples,True,2,-1910.210571
52,52,True,True,31,31.0,True,True,False,False,False,...,20850.0,14338.0,femme,homme,1,1.0,Couples,True,2,-198.216736
54,54,True,True,31,31.0,True,True,False,False,False,...,20850.0,19202.0,femme,homme,1,1.0,Couples,True,1,-198.216736
56,56,True,False,37,31.0,True,False,False,False,False,...,22647.0,0.0,femme,homme,1,1.0,Couples,False,0,-517.940369
58,58,True,True,31,31.0,True,True,False,False,False,...,20850.0,19067.0,femme,homme,1,1.0,Couples,True,2,-198.216736
63,63,True,True,34,31.0,True,True,False,False,False,...,32146.0,36018.0,femme,homme,1,1.0,Couples,True,3,-1910.210571
70,70,True,True,31,32.0,True,True,False,False,False,...,20850.0,21867.0,femme,homme,1,1.0,Couples,True,2,-198.216736
76,76,True,True,30,32.0,True,True,False,False,False,...,37990.0,27436.0,femme,homme,1,1.0,Couples,True,2,-2632.097900
80,80,True,True,38,32.0,True,True,False,False,False,...,21746.0,43649.0,femme,homme,1,1.0,Couples,True,1,-357.462036
85,85,True,False,31,33.0,True,False,False,False,False,...,20850.0,0.0,femme,homme,1,1.0,Couples,False,0,-198.216736
90,90,True,True,30,33.0,True,True,False,False,False,...,37990.0,38083.0,femme,homme,1,1.0,Couples,False,0,-2632.097900
108,108,True,True,34,34.0,True,True,False,False,False,...,32146.0,23909.0,femme,homme,1,1.0,Couples,True,1,-1910.210571
110,110,True,True,31,34.0,True,True,False,False,False,...,20850.0,16867.0,femme,homme,1,1.0,Couples,True,3,-198.216736
113,113,True,True,34,34.0,True,True,False,False,False,...,32146.0,20250.0,femme,homme,1,1.0,Couples,True,2,-1910.210571
114,114,True,True,31,34.0,True,True,False,False,False,...,20850.0,27967.0,femme,homme,1,1.0,Couples,False,0,-198.216736
121,121,True,True,34,34.0,True,True,False,False,False,...,32146.0,3135.0,femme,homme,1,1.0,Couples,False,0,-1910.210571
123,123,True,False,30,34.0,True,False,False,False,False,...,37990.0,0.0,femme,homme,1,1.0,Couples,True,2,-2632.097900
132,132,True,False,34,34.0,True,False,False,False,False,...,32146.0,0.0,femme,homme,1,1.0,Couples,False,0,-1910.210571
140,140,True,False,30,35.0,True,False,False,False,False,...,37990.0,0.0,femme,homme,1,1.0,Couples,False,0,-2632.097900
142,142,True,True,31,35.0,True,True,False,False,False,...,20850.0,28038.0,femme,homme,1,1.0,Couples,False,0,-198.216736
145,145,True,True,30,35.0,True,True,False,False,False,...,37990.0,16808.0,femme,homme,1,1.0,Couples,False,0,-2632.097900
146,146,True,True,31,35.0,True,False,False,False,False,...,20850.0,0.0,femme,homme,1,1.0,Couples,False,0,-198.216736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6041,6041,True,NaN,60,NaN,True,NaN,False,NaN,False,...,75321.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-10943.817383
6042,6042,True,NaN,60,NaN,True,NaN,False,NaN,False,...,67093.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-9111.341797
6043,6043,True,NaN,60,NaN,True,NaN,False,NaN,True,...,29874.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1679.175537
6045,6045,True,NaN,60,NaN,True,NaN,False,NaN,False,...,31473.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1841.746460
6046,6046,True,NaN,61,NaN,True,NaN,False,NaN,False,...,22998.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-580.227722
6047,6047,True,NaN,61,NaN,True,NaN,False,NaN,False,...,52393.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-5837.166504
6048,6048,True,NaN,61,NaN,True,NaN,False,NaN,False,...,69813.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-9716.958008
6049,6049,True,NaN,61,NaN,True,NaN,False,NaN,False,...,51474.0,NaN,homme,NaN,2,NaN,homme solo,False,0,-5632.545410
6051,6051,True,NaN,61,NaN,True,NaN,False,NaN,False,...,40068.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-3092.232178
6055,6055,True,NaN,61,NaN,True,NaN,False,NaN,False,...,67378.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-9174.681641
6061,6061,True,NaN,61,NaN,True,NaN,False,NaN,True,...,35968.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-2298.843018
6062,6062,True,NaN,61,NaN,True,NaN,False,NaN,False,...,26197.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-1149.416992
6063,6063,True,NaN,62,NaN,True,NaN,False,NaN,False,...,47823.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-4819.343750
6064,6064,True,NaN,62,NaN,True,NaN,False,NaN,True,...,30172.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-1709.477905
6068,6068,True,NaN,62,NaN,True,NaN,False,NaN,False,...,33811.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-2079.539307
6070,6070,True,NaN,62,NaN,True,NaN,False,NaN,False,...,358789.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-121537.898438
6073,6073,True,NaN,62,NaN,True,NaN,False,NaN,False,...,31330.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1827.270386
6074,6074,True,NaN,62,NaN,True,NaN,False,NaN,False,...,29052.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1595.697632
6076,6076,True,NaN,62,NaN,True,NaN,False,NaN,False,...,30094.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1701.648315
6079,6079,True,NaN,62,NaN,True,NaN,False,NaN,True,...,46062.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-4427.353027
6084,6084,True,NaN,63,NaN,True,NaN,False,NaN,False,...,27250.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-1336.758179
6085,6085,True,NaN,63,NaN,True,NaN,False,NaN,False,...,24934.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-924.728394
6086,6086,True,NaN,63,NaN,True,NaN,False,NaN,False,...,33148.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-2012.062988
6092,6092,True,NaN,63,NaN,True,NaN,False,NaN,False,...,30813.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-1774.749146
6095,6095,True,NaN,64,NaN,True,NaN,False,NaN,False,...,43843.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-3933.121582
6098,6098,True,NaN,64,NaN,True,NaN,False,NaN,False,...,109227.0,NaN,homme,NaN,2,NaN,homme solo,False,0,-19445.802734
6099,6099,True,NaN,64,NaN,True,NaN,False,NaN,False,...,20340.0,NaN,homme,NaN,3,NaN,homme solo,False,0,-107.441895
6102,6102,True,NaN,64,NaN,True,NaN,False,NaN,False,...,31920.0,NaN,homme,NaN,0,NaN,homme solo,False,0,-1887.201050
6103,6103,True,NaN,64,NaN,True,NaN,False,NaN,False,...,22444.0,NaN,homme,NaN,2,NaN,homme solo,False,0,-481.729126
6292,6292,True,NaN,89,NaN,True,NaN,False,NaN,False,...,25028.0,NaN,homme,NaN,2,NaN,homme solo,False,0,-941.598022